  server:
    port: 8443 # Define a custom port instead of the default 8080
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    use-forward-headers: true



  spring:
    main:
      allow-bean-definition-overriding: true

  swagger:
      paths: /v2/se.atg.service.member.api-docs,/swagger-ui.html,/swagger-resources/**,/webjars/**,/favicon.ico

  keycloak:
      auth-server-url: https://sso-ssoha.b9ad.pro-us-east-1.openshiftapps.com/auth
      realm: master
      resource: getaway
      ssl-required: "external"
      confidential-port: 0
      principal-attribute: preferred_username
      bearer-only: true
