  server:
    port: 8443 # Define a custom port instead of the default 8080
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    use-forward-headers: true



  spring:
    main:
      allow-bean-definition-overriding: true
